* TODO 00 It shall be possible to store stories in Emacs Org-Mode format

  As a software developer I need my stories in a very easy to use format,
  like Emacs Org-Mode to make my agile mindset easier to realize.

* TODO 01-20 It shall be possible to make fuzzy estimate ranges of a story

  As a product owner I want to be able to keep stories estimated even if
  they are not well defined yet.

* TODO 03 It shall be possible to have accurate estimates of a story

  As a product owner I need to be able to have single (and accurate)
  estimates of stories in the backlog as the stories grow more defined.

* DONE 05 It shall be possible to toggle stories to DONE to track progress
  SCHEDULED: <2017-01-03> DEADLINE: <2017-01-05>

  As a product owner I need to be able to track story progress and to be
  able to calculate velocity over time.

  * The SCHEDULED Emacs Org-Mode tag is the date when the story was started.
  * The DEADLINE Emacs Org-Mode tag is the date when the story was done.

  This is actually MANDATORY to be able to consider a story to be done.

* DONE 06 Another story to place in second sprint to verify blvelocity
  SCHEDULED: <2017-01-09> DEADLINE: <2017-01-10>
